name: Deploy React App to GitHub Pages

on:
  push:
    branches: [ main ]  # or your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # or whatever version you're using
    
    - name: Install dependencies
      run: npm install
    
    - name: Update browserslist
      run: npx update-browserslist-db@latest
    
    - name: Build
      run: CI=false npm run build
    
    - name: Check for CNAME file
      id: check-cname
      run: |
        if [ -f CNAME ]; then
          echo "::set-output name=exists::true"
        else
          echo "::set-output name=exists::false"
        fi
    
    - name: Copy CNAME
      if: steps.check-cname.outputs.exists == 'true'
      run: cp CNAME build/CNAME
    
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages  # The branch the action should deploy to.
        folder: build  # The folder the action should deploy.
        token: ${{ secrets.GITHUB_TOKEN }}